version: "3"

services:
  craw-web-api:
    container_name: craw-web-api
    image: vunam2000/craw-web-api
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - craw-web-api
 
networks:
  craw-web-api:
    driver: bridge